# Generated by Django 3.0.14 on 2022-11-04 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Количество комнат')),
                ('slug', models.CharField(blank=True, max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Количество комнат',
                'verbose_name_plural': 'Количество комнат',
            },
        ),
        migrations.AlterField(
            model_name='ads',
            name='count_rooms',
            field=models.ForeignKey(default='Не указано', on_delete=django.db.models.deletion.CASCADE, to='scraping.CountRooms', verbose_name='Количество комнат'),
        ),
    ]
