# Generated by Django 3.0.14 on 2022-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20221105_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
