# Generated by Django 3.0.14 on 2022-11-06 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20221105_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='condition',
            new_name='conditions',
        ),
        migrations.AlterField(
            model_name='ads',
            name='material',
            field=models.ForeignKey(default='Не указано', on_delete=django.db.models.deletion.SET_DEFAULT, to='scraping.Material', verbose_name='Материал'),
        ),
    ]
